#!/bin/bash
# Version 21

qtMinVer="6.6"
kfMinVer="6.0"
plasmaMinVer="6.0"
filenameTag="plasma${plasmaMinVer}"
filenameTag=`echo "$filenameTag" | sed 's/\./\-/'`
python3 ./kpac build --tag "$filenameTag"
